### PR TITLE
New shodan map

### PR DESCRIPTION
**Pull request by simonwiles**
I think this is about as good as I can get it for now.  After much fiddling, I think everything lines up beautifully now.  Some notes:

1) I've recalculated the widths of the the shodans, dans, and acts based on a computed length (basically the time from the start time to the beginning of the next shodan/dan/act) -- see d1fae2fb.  This is a bit involved, tbh, and if you're thinking "that code is a bit tortuous; surely that indicates a fundamental inadequacy in the underlying data model?" you'd be right :)

2) The result at that point still looked a bit shonky because of the various overlapping borders on shodans/dans/acts, and the fact that this structure is not replicated in the headings.  To address this, I've used three strategies:
  i) clear some `border-right` styles on `:last-child` elements;
  ii) apply some of the styling to `absolute`ly positioned `::before` pseudo-elements; and
  iii) switched some of the border styles to full-opaque instead of semi-transparent, to prevent stacking.

W/r/t iii) above, I've used a new SASS variable -- @inefable please change this to your satisfaction as you desire.  The colours of the lines still look a little different in places, due to the optical illusion created by neighbouring colours -- this could perhaps be compensated for if it is found to be offensive, but would probably have to be done manually.

Requesting two reviews -- @inefable for the design, and @broadwell for your eagle-eyes, please!

### CODE REVIEW

**Comment by inefable** [comment]
Looks good to me, @simonwiles! I've added some changes to visualize correctly the shodan timeline on level 2. I've also refactored some SCSS but it's basically the same 😊

**Comment by simonwiles** [comment]
@inefable are you able to take a look at addressing these?

**Comment by inefable** [comment]
@broadwell Thanks for your comments! 
I've fixed the changing height when hovering the shodan on Level 2. Both cases were related to the same bug. I think the one about the collapsed small-ITI was because of a change on the border of the element. I've corrected that too, so it shouldn't (hopefully) be a problem any longer.

**Comment by broadwell** [comment]
@inefable Thanks, your updates fix the "shrinking block" issue with the L2 shōdan map. I only notice one more weirdness with the L2 map, which is that the highlighting of the active shōdan can disappear when a different shōdan within the same _dan_ is moused over. For example, if you're at `/kokaji/sashi/` and mouse over the adjacent sections in the L2 map (Kuri or Kuse), the dark highlighting of Sashi disappears temporarily. This only happens for shōdan within the same _dan_ ("Shite performs", in this case). Probably the desired behavior is for the current shōdan to remain highlighted even when its neighbors are moused over? The moused-over neighbor should be highlighted too, of course; perhaps it would be preferable for these highlight colors (active shōdan vs. moused-over shōdan) to differ somewhat, but I have no preference about that.

Other than this, it looks good to go!

**Comment by broadwell** [comment]
The latest update looks good to me! I do think we may want to consider making the expanded L2 map look even more like the L1 map (for example, by adding the act or _dan_ divisions) -- the current hover behavior is still a little odd, in that the low-IQI sections get a muted highlight when you mouse above them, but the tall blocks can only be moused over -- but that's probably a judgment call for the PIs, and not necessary to address before merging this.

**Pull request merged**
